version: "2"
services:
  pokedex: 
    build: .
    container_name: pokedex-graphql
    image: mrhus/pokedex
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; nodemon -L /usr/app/src/index.js'
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/pokedex
      - PORT=3000
    volumes:
      - "$PWD/src:/usr/app/src"
  db:
    image: postgres
    ports: 
      - 3001:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pokedex